project:
  type: website

website:
  title: "Parachain Health Test20"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: R_Dashboard.Rmd
        text: R Dashboard
      - href: Python_Dashboard.qmd
        text: Python Dashboard
      - href: Slides.qmd
        text: Slides

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
execute:
  freeze: auto

